name: vibe_day
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^8.1.2
  bloc_presentation: ^0.3.0
  cached_network_image: ^3.2.3
  camera: ^0.10.5+5
  collection: ^1.17.2
  cupertino_icons: ^1.0.6
  dio: ^5.3.2
  dotted_border: ^2.0.0+3
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  extended_nested_scroll_view: ^6.1.2
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^14.1.1
  flutter_map: ^5.0.0
  flutter_native_splash: ^2.3.2
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  formz: ^0.6.0
  freezed_annotation: ^2.4.1
  fresh_dio: ^0.4.1
  geolocator: ^10.0.1
  geocoding: ^2.1.1
  go_router: ^10.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  hydrated_bloc: ^9.1.2
  image_picker: ^1.0.4
  intl: ^0.19.0
  json_annotation: ^4.8.1
  latlong2: ^0.9.0
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^10.4.3
  phosphor_flutter: ^2.0.0
  retrofit: ^4.0.1
  scrollable_positioned_list: ^0.3.8
  share_plus: ^11.0.0
  shared_preferences: ^2.2.1
  signature: ^5.4.0
  url_launcher: ^6.1.14
  webview_flutter: ^4.2.4
  lucide_icons: ^0.257.0

cupertino_icons: ^1.0.8

dev_dependencies:
  bloc_test: ^9.1.3
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^7.0.8
  very_good_analysis: ^5.1.0

  flutter_lints: ^5.0.0

flutter_launcher_icons:
      android: "launcher_icon"
      ios: true
      image_path: "assets/images/vibeday_app_logo.png"

flutter_native_splash:
      background_image: assets/images/vibeday_splashscreen.png

      android_12:
        image: assets/images/vibeday_splashscreen.png
        icon_background_color: "#ffffff"


flutter_gen:
  output: lib/assets
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/color/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 800
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 900
